---
- name: Assert required variables
  ansible.builtin.import_tasks: assert.yaml

- name: Create remnanode directory
  ansible.builtin.file:
    path: "{{ remnanode_path }}"
    owner: root
    group: root
    mode: "0750"
    state: directory

- name: Create compose file
  ansible.builtin.template:
    src: docker-compose.yaml.j2
    dest: "{{ remnanode_path }}/docker-compose.yaml"
    owner: root
    group: root
    mode: "0640"

- name: Create env file
  ansible.builtin.template:
    src: env.j2
    dest: "{{ remnanode_path }}/.env"
    owner: root
    group: root
    mode: "0600"
  register: remnanode_env

- name: Create Caddy config directory
  ansible.builtin.file:
    path: "{{ remnanode_caddy_config_path }}"
    owner: root
    group: root
    mode: "0750"
    state: directory
  when: remnanode_caddy_enable

- name: Create Caddyfile
  ansible.builtin.template:
    src: Caddyfile.j2
    dest: "{{ remnanode_caddy_config_path }}/Caddyfile"
    owner: root
    group: root
    mode: "0640"
  when: remnanode_caddy_enable
  register: remnanode_caddyfile

- name: Deploy remnanode
  community.docker.docker_compose_v2:
    project_src: "{{ remnanode_path }}"
    remove_orphans: true
    wait: true
    recreate: "{{ 'always' if remnanode_env is changed else 'auto' }}"

- name: Reload Caddy
  community.docker.docker_compose_v2_exec:
    project_src: "{{ remnanode_path }}"
    service: remnanode-caddy
    command: caddy reload --config /etc/caddy/Caddyfile
  when:
    - remnanode_caddy_enable
    - remnanode_env is not changed
    - remnanode_caddyfile is changed

- name: Configure logrotate
  ansible.builtin.import_tasks: logrotate.yaml
  when: remnanode_logrotate_enable
