---
default_user: ansible
ssh_public_key_file: ~/.ssh/id_ed25519.pub

ansible_ssh_private_key_file: ~/.ssh/id_ed25519

firewall_allowed_tcp_ports:
  - "22"
  - "80"
  - "443"

remnawave_backend_tag: 3.1.0
remnawave_sub_page_tag: 8.0.0
remnawave_caddy_tag: 2.11.4

remnanode_node_tag: 3.0.0
remnanode_caddy_tag: 2.11.4
